[package]
name = "lox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.9"
lazy_static = "1.4.0"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
